### ISSUE TITLE
[ERROR/WARNING] Error & Warning when opening world

### ISSUE THREAD

**Issue by Xironsama** [League-of-Foundry-Developers/simplefog#103]
When starting/running my world, i get 1 warning and 1 error from Simplefog. Since Running V0.3.0 i have been getting the warning seen in the image attached. Since V0.3.1 i have been getting the error seen in the image attached. Is this an issue with the module, a conflict with other modules or an issue on my world/pc side? Running Foundry from an Oracle server.

![simplefog error](https://user-images.githubusercontent.com/131367060/233370386-9e4ab353-c4fe-43f0-922a-4893ec58b9a1.png)

**Comment by Xironsama** [comment]
Oh and everytime i switch to a scene that doesnt have fog i get the error below.

![simplefog error 2](https://user-images.githubusercontent.com/131367060/233372151-cb998855-f509-4e52-bab6-52ba8e93498d.png)

**Comment by HenningTimm** [comment]
I can reproduce this. As a workaround you can enable fog, make one change (i.e. uncover one part of the map), then deactivate fog for the scene again. A bit clunky, but gets rid of the error.
Maybe the history variable/ attribute is not initialized and is only created after the first action?
