### ISSUE TITLE
[BUG]  The Simplefog section in Configure Game Settings has two entries that look to be missing actual names

### ISSUE THREAD

**Issue by steveculshaw** [League-of-Foundry-Developers/simplefog#116]
**Module Version:** v0.3.4

**Describe the bug**
The Simplefog section in Configure Game Settings has two entries that look to be missing actual names; `simplefog.setting.reset.name` and `simplefog.setting.debug.name`

**To Reproduce**
1. Go to Configure Game Settings
2. Scroll down to 'Simplefog'

**Expected behavior**
Add setting correct names.

**Screenshots**
Missing text in dialog ...
<img width="434" alt="image" src="https://github.com/League-of-Foundry-Developers/simplefog/assets/64320/c151b9e2-2b68-449f-8e5a-8408561144fa">

**Foundry Version:** 
11.305 

**Game System:** 
Savage Worlds Adventure Edition 3.0.6

**Additional context**
None

**Comment by UranusBytes** [comment]
The simplefog from this repo is dead since it couldn't get updated in admin console. I would suggest reporting this bug (if still applicable) here - https://github.com/mclemente/simplefog
