### ISSUE TITLE
[BUG] Simplefog still allows players to see doors on the hidden portion of map

### ISSUE THREAD

**Issue by steveculshaw** [League-of-Foundry-Developers/simplefog#117]
**Module Version:** v0.3.4

**Describe the bug**

**To Reproduce**
1. Enable Simplefog for scene with doors
2. See error

**Expected behavior**
The door icons in the hidden area should not be displayed to the players

**Screenshots**
Simplefog layer in grey, players can see the two door icons
<img width="235" alt="image" src="https://github.com/League-of-Foundry-Developers/simplefog/assets/64320/6e7705ad-bb88-49df-b9e5-a8153d7e5d9c">

**Browser:**
Chrome

**Foundry Version:** 
11.350 

**Game System:** 
Savage Worlds Adventure Edition 3.0.6

**Additional context**
None

**Comment by UranusBytes** [comment]
Unfortunately, this is not something that can be fixed.  Doors are on the "interface" layer which is above the simplefog layer, and lowering it would lower many other necessary controls.

**Comment by steveculshaw** [comment]
Ah ha ... bummer  :-(
Thanks for response
