### ISSUE TITLE
[BUG] Line at the bottom of the screen not covered by fog, allowing players to reveal the entire map.

### ISSUE THREAD

**Issue by FoundryHater1337** [League-of-Foundry-Developers/simplefog#118]
On the bottom of the screen, is a thin line that is not covered by simplefog. 
This moves with the camera, so a player can use this to literally look at the entire map underneath the fog, making the module completely useless.

![b7b444347e3f91947d4c69bbac82cb21](https://github.com/League-of-Foundry-Developers/simplefog/assets/144299940/5f4894d4-0271-4896-9998-abda93e4ca32)
![c64e3da032dd4e641dde3e67fed086f4](https://github.com/League-of-Foundry-Developers/simplefog/assets/144299940/346ada2b-5f20-4be3-9235-68d797d3cd80)

**Comment by UranusBytes** [comment]
Are you still experiencing this behavior?  If so, what browser and platform are you on?

This has sporadically be reported, but I've never been able to reproduce it...

**Comment by UranusBytes** [comment]
The simplefog from this repo is dead since it couldn't get updated in admin console. I would suggest reporting this bug (if still applicable) here - https://github.com/mclemente/simplefog
