### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by YenBenGrey** [League-of-Foundry-Developers/simplefog#120]
**Module Version:** v0.3.4

**Describe the bug**
When activating any scene this error occurs. In the screenshot

**To Reproduce**
1. Go to a scene
2. Click on another scene and activate
4. See error in console

**Expected behavior**
There should not be an error

**Screenshots**
![image](https://github.com/League-of-Foundry-Developers/simplefog/assets/98095856/8080924b-5ddf-40f4-9810-9fd7b1c945cc)
**Browser:**
 Chrome

**Foundry Version:** 
11.314
**Game System:** 
DND5e
**Additional context**
I have no idea what problem it is causing

**Comment by UranusBytes** [comment]
The simplefog from this repo is dead since it couldn't get updated in admin console.  I would suggest reporting this bug (if still applicable) here - https://github.com/mclemente/simplefog
