### ISSUE TITLE
Scene can't be rendered just for players, error on console

### ISSUE THREAD

**Issue by JJBocanegra** [League-of-Foundry-Developers/simplefog#14]
I'm having a problem when I'm with the players on another scene and change to this concrete scene. 

### How to recreate

1.  Player P is on scene "Taberna de la Canción Élfica" (any other scene is valid)
2. I change the scene to "Termas (Con paredes y simplefog)" (attached [Problematic map.zip](https://github.com/League-of-Foundry-Developers/simplefog/files/5860380/fvtt-Scene-La_mazmorra_de_los_tres_muertos_.Copy.zip))
3. The player sees a black screen but I can see the scene
4. The player need to refresh the browser to see the scene

### Investigation
This is what I see when the new scene change has loaded, the player is showed on the previous scene.
![image](https://user-images.githubusercontent.com/5797636/105602900-c44fb380-5d95-11eb-9fad-fa2d9e7450eb.png)

When the player open the console, he sees this error:
![image](https://user-images.githubusercontent.com/5797636/105601445-5efbc280-5d95-11eb-812e-48a2aaf21575.png)

The problem seems to be on `js/sightLayerUpdate.js` file, line 19 while trying to access the property `x` of the object `p`:
![image](https://user-images.githubusercontent.com/5797636/105602031-86eb2600-5d95-11eb-8bfa-25576ad1e87a.png)

Here are the guilty variables values when the error happens:
![image](https://user-images.githubusercontent.com/5797636/105602258-98ccc900-5d95-11eb-971d-317147e3e72e.png)

And that's all I can do without knowing how the module works :( hope it helps tracking the problem.

 If you need more help I can create a world with the recreation of the bug with the needed scenes and modules ;)

**Comment by crhampton1** [comment]
Sorry for delay, I have been sick. Back at it now working on next update and will hopefully have this bug fixed then!

**Comment by JJBocanegra** [comment]
Sorry to hear that, I hope you are better now, this isn't a top priority bug after all ;)

**Comment by crhampton1** [comment]
Okay, I could not replicate. However, I think I found the issue and it was in a feature that hasn't worked since Foundry updated their new layer system, so I just removed it. Can you give it a try and see if you still have issues. I have a few other ideas if that doesn't work.

Thanks!

**Comment by JJBocanegra** [comment]
It seems to work perfect now, thanks!!
