### ISSUE TITLE
[Bug] Simple Fog only shown for some players

### ISSUE THREAD

**Issue by Gnurrf** [League-of-Foundry-Developers/simplefog#16]
Today, map hiding using simple fog worked for four out of five players. For the fifth, the complete map was visible.

**Comment by crhampton1** [comment]
Sorry for delay, I have been sick. Back at it now working on next update.

I am thinking this is related to a bug in another issue, so I am going to merge unless you have more details so I see it's separate. It sounds like a bug I'm fixing though.

**Comment by crhampton1** [comment]
Okay, I could not replicate. However, I think I found the issue and it was in a feature that hasn't worked since Foundry updated their new layer system, so I just removed it. Can you give it a try and see if you still have issues. I have a few other ideas if that doesn't work.

Thanks!

**Comment by Gnurrf** [comment]
Ok, will try. Replicating it is going to he difficult for me as well, as the problem occurred only for a single player. 

Understanding is a three-edged sword.

**Comment by crhampton1** [comment]
I have had a few mention that they are not having this problem anymore. I am going to go ahead and close this but if it happens again feel free to reopen!! Thanks!
