### ISSUE TITLE
Updates for 0.7.8 and 0.7.9

### ISSUE THREAD

**Issue by moorepants** [League-of-Foundry-Developers/simplefog#17]
Foundry has released 0.7.8 and 0.7.9 and this module supports up to 0.7.7. Compatibility needs to be assessed and the module updated so we can upgrade to newer Foundry versions.

**Comment by akrigline** [comment]
There's a sea of compatibility risk flags in module territory, all it means is the number hasn't been incremented in the manifest.

By and large someone will have chimed in if something breaks in an update, especially with a module as popular as simplefog.

I know of no issues related to 079. As always backup your data before updating.

**Comment by moorepants** [comment]
Yes, I'm suggesting that the number should be incremented if it is deemed compatible with newer versions of Foundry.

**Comment by crhampton1** [comment]
Thanks! I've been out due to sickness, but finishing up next version soon. Will also have this updated as well.

**Comment by crhampton1** [comment]
Updated!
