### ISSUE TITLE
How to install? Posting the link the JSON fails in FoundryVTT setup menu.

### ISSUE THREAD

**Issue by Sonny-Crockett** [League-of-Foundry-Developers/simplefog#2]
Will this auto-update once installed correctly in Foundry? And it will pull from this repo and not the old one?

Thanks for making it work again.

**Comment by akrigline** [comment]
@Sonny-Crockett to install this fork, you first will have to uninstall the old module, then install based on this manifest url:
```
https://raw.githubusercontent.com/League-of-Foundry-Developers/simplefog/master/module.json
```

**Comment by crhampton1** [comment]
@Sonny-Crockett , All your fog should remain, event after uninstalling and re-installing the new fork.
