### ISSUE TITLE
Painting Away Fog reveals map notes to players

### ISSUE THREAD

**Issue by Col45** [League-of-Foundry-Developers/simplefog#22]
Players with no journal permission can see map notes when on the notes view and the gm paints away fog. When players do anything to the UI, the map notes disappear.

Found the culprit, seems to be related to the module Pin Fixer.

**Comment by crhampton1** [comment]
Can you tell me what version you are on of SimpleFog? Please update to 0.1.17 if not there and see if that fixes it!
