### ISSUE TITLE
Wrong version number in the release

### ISSUE THREAD

**Issue by lunactic** [League-of-Foundry-Developers/simplefog#24]
I think there is currently a version mismatch in the module.json here on GitHub and the one in the release.zip of the 0.1.17 release, leading to an infinite update loop.

The module.json inside the zip file of the 0.1.17 release still has version as 0.1.16, and I think this leads to Foundry not realizing that the latest version is installed.

**Comment by moorepants** [comment]
Same issue. I cannot update past 0.1.16.

**Comment by crhampton1** [comment]
Sorry everyone. Work and life have been intense past couple of weeks.

I have updated the zip so it points correctly to the 0.1.17 and then added the module.json. Just checked and both are pointing to 0.1.17.

Can you try and update and let me know if it updates correctly?

Thanks!

**Comment by kernalkue** [comment]
Seems good to me now

**Comment by moorepants** [comment]
Yes, installation worked for me to.

**Comment by crhampton1** [comment]
Great!
