### ISSUE TITLE
Simplefog menu button becomes unresponsive after initial scene selection

### ISSUE THREAD

**Issue by funkybrain** [League-of-Foundry-Developers/simplefog#28]
Currently running Foundry 0.7.9 and Simplefog 0.1.11.

If I load the module and open a scene, I can select the sf button, and paint / remove fog etc. no issues.

But as soon as I leave the scene and try another, or come back to the original scene, or pick another tool, the sf button is unresponsive. I can click as much as I want, I will not be able to open the sf icons and manipulate the fog.

**Comment by crhampton1** [comment]
Hey! Simplefog 0.1.11 is behind the most current version of 0.1.17. At some point, Foundry re-did a bunch of how they rendered scenes and so only, I think, 0.1.15 and above will work with that version of Foundry. If you upgrade it should resolve that issue.

**Comment by funkybrain** [comment]
Somehow it marks the module as "Current" when I check update. I will try and uninstall and reinstall see if that works.

Edit: yup, that did the job. Not sure why auto-update did not work...

**Comment by crhampton1** [comment]
Ah, yeah if you had it before we forked it, I think 0.1.11 is the final release from Vance. Try removing it completely and reinstalling it. Here is the package.json link if you want to use that, but searching in the list of modules should have the fork. It should also keep anything you have already done.
https://raw.githubusercontent.com/League-of-Foundry-Developers/simplefog/0.1.17/module.json 

Edit: Saw your update, glad it worked!!
