### ISSUE TITLE
Version 0.7.10 Clients unable to reveal Fog Image layer via token vision.

### ISSUE THREAD

**Issue by Ssezra** [League-of-Foundry-Developers/simplefog#33]
Clients seem to be unable to reveal the Fog image layer when moving a token with vision.  On the client side the scene displays the fog image layer and tokens will move underneath the layer without revealing.

On the GM side you can reveal a clients fog image layer with the brush tool; but it will not reveal with a token moving around with vision.

**Comment by moorepants** [comment]
I don't think that this module supports token movement revealing the fog. The builtin fog of war system in Foundry does that. This module is for the GM to manually reveal the fog of war.
