### ISSUE TITLE
Simple Fog doesn't hide door icons

### ISSUE THREAD

**Issue by Conandy1970** [League-of-Foundry-Developers/simplefog#34]
I was just trying to set up some partially explored maps for my players to be able to view without having to have their tokens in the map (for instance, partially explored levels of a house that they are still in but they are now on a different floor).  In order to be able to allow them to view where they have been, I was trying to use Simple Fog and to turn off Token Vision for the scene to continue to hide the places they didn't visit.  

This works great, except for the fact that Simple Fog doesn't hide the little "door" icons for clickable doorways in the still fogged areas if Token Vision is turned off for the scene.  The player sees the little doorway icon floating in the blackness, so they know that there is a door in there.  

If I change the door type to "secret", it does disappear.  But I am afraid I'll forget the change it back later.

**Comment by moorepants** [comment]
I experienced this recently also. I had placed regular doors, think they'd be hidden by the fog of war, but my players could see them all on top of the fog of war layer.

**Comment by jegasus** [comment]
I'm here to second this! Just noticed the issue a couple of sessions ago. I'm currently using simplefog version 0.1.18 and Foundry 0.8.9.

**Comment by CaffeinatedTech** [comment]
This is still a problem in version 0.2.1 in foundry 9.269.  Is changing doors to "secret" or just removing doors what everyone is doing to get around this?

**Comment by UranusBytes** [comment]
The doors are in the same layer as the main HUD (at top), so they can't be put below the simple fog layer.  Best that could possibly be done is to disable the rendering of the door icons, which as I best understand eliminates any reason for using them in the first place (unless someone has a use case they'd share)
