### ISSUE TITLE
Simple Fog doesn't hide colored lights.

### ISSUE THREAD

**Issue by eivindhusby** [League-of-Foundry-Developers/simplefog#36]
![image](https://user-images.githubusercontent.com/85963179/122110245-9b03f280-ce1e-11eb-8fb3-7adfd4fa6898.png)
![image](https://user-images.githubusercontent.com/85963179/122110256-9dfee300-ce1e-11eb-8658-592148b58158.png)
If I set a color on a light, it shows through the Simple Fog layer.
Running on Foundry 8.7

**Comment by eivindhusby** [comment]
It also doesn't seem to block weather effects.

**Comment by UranusBytes** [comment]
As best as I can tell, this issue no longer exists.  If this is not the case, please provide some additional details (screenshots) on how you've configured the light.
