### ISSUE TITLE
Pathfinder 1e tooltips show up even if tokens are behind fog of war

### ISSUE THREAD

**Issue by moorepants** [League-of-Foundry-Developers/simplefog#37]
First reported here:

https://gitlab.com/Furyspark/foundryvtt-pathfinder1/-/issues/895

but the developers of the system believe it's a bug in simplefog.

My players informed me that they can move their mouse around areas on a map covered by the simplefog fog of war and the tooltips for creatures behind the fog will appear. Here is a screenshot. Note that my mouse is on the right screen (player screen). The tooltip shows up in the bottom right of the player screen.

![Screenshot from 2021-06-20 08-27-16](https://user-images.githubusercontent.com/276007/122680902-e9840900-d1f1-11eb-9273-707691e4188d.png)

Foundry 0.7.10

Pf1e 0.77.24

Simplefog 0.1.17

pf1e developer note:

> Can't reproduce this without Simple Fog, so it seems to be bug in that module, causing hoverToken hook to fire on hidden tokens when it shouldn't.

**Comment by UranusBytes** [comment]
As best as I can tell, this is no longer an issue.  If still a real issue, please provide updated details.
