### ISSUE TITLE
Can't get image layer to work

### ISSUE THREAD

**Issue by Wokeye27** [League-of-Foundry-Developers/simplefog#38]
Hi Folks, 
Thanks for the great module. 
I've tried a bunch of settings but cannot get the image-as-fog thing happening.   I've got two of the same images as background and image, all my players see is black fog.
Are there any limitations/tricks that apply to this feature that are not mentioned? Any specific other settings in the module needed to make it work - I've tried a bunch of combinations but no luck.

**Comment by thagrasshoppa** [comment]
I have been able to make this work, friend me on Discord thagrasshoppa#9562 if you still want to troubleshoot it!
