### ISSUE TITLE
Players can view the oncovered map areas via a sliver at the bottom of the screen

### ISSUE THREAD

**Issue by moorepants** [League-of-Foundry-Developers/simplefog#40]
One of my players sent this screen shot of the recent game session:
![Clipboard24](https://user-images.githubusercontent.com/276007/138320168-c3deb0f0-73d1-4a1b-9b06-146f1be9cf2b.jpg)

If you look closely just above the windows taskbar you can see a horizontal sliver of exposed map. If you pan around enough you can use that sliver to see the uncovered portions of the map and make some guesses at where enemies are and other things.

He's using Edge on Windows.

Foundry version: 0.8.8

Pathfinder 1: 0.79.6

**Comment by UranusBytes** [comment]
As best as I can tell, this is no longer an issue.  If still a real issue, please provide updated details.
