### ISSUE TITLE
Toggle Notes Display doesn't work for players on maps with Simple Fog

### ISSUE THREAD

**Issue by SwordofSpirit** [League-of-Foundry-Developers/simplefog#41]
If the player has the Journal Notes layer selected they can see the notes, but toggling the display on doesn't cause the notes to stay visible when on different layers. This issue only happens on maps with Simple Fog active.

**Comment by UranusBytes** [comment]
As best as I can tell, this is no longer an issue.  If still a real issue, please provide updated details.
