### ISSUE TITLE
tiny strips revealed at bottom and right of screen on firefox/win10 client

### ISSUE THREAD

**Issue by modzy2** [League-of-Foundry-Developers/simplefog#42]
Strips of maybe a couple of pixels wide of the hidden map are revealed at the bottom and right edges of the screen (although the strip on the right is only visible with sidebar collapsed).  Was only visible on Firefox 93.0 on WIndows 10 client.  (with chrome on the same computer, the issue does not occur).

**Comment by modzy2** [comment]
Oops, just found it actually is happening on Chrome as well.

**Comment by moorepants** [comment]
This is the same as issue #40.

**Comment by UranusBytes** [comment]
As best as I can tell, this is no longer an issue.  If still a real issue, please provide updated details.
