### ISSUE TITLE
Any Plans For V9 Update?

### ISSUE THREAD

**Issue by PhluXx1** [League-of-Foundry-Developers/simplefog#44]
Really love this module and would love to see a V9 update. Been holding off upgrading to V9 as Simplefog is so important for my campaign. Any plans for a V9 update and if so when?

**Comment by paulcheeba** [comment]
So far it has been working for me on V9, I have not tried any new simplefog additions to a new world but my previously set up world with simple fog is functioning as it should after migrating the world to v9 and latest DND5e.

**Comment by PhluXx1** [comment]
I'm glad it's working for you but it's not the case for everyone such as with issue #45. This module needs a v9 update.

**Comment by UranusBytes** [comment]
Resolved in 0.2.0
