### ISSUE TITLE
Journal Pins do not show up with V9

### ISSUE THREAD

**Issue by kalak** [League-of-Foundry-Developers/simplefog#45]
Previously, with 0.8.x, with the overlay image, journal pins would show up correctly over the overlay as long as the journal sidebar was selected, or journal pins clicked.

With V9, however, neither the journal sidebar or pins clicked allows pins to be visible over the overlay image.

**Comment by kalak** [comment]
![image](https://user-images.githubusercontent.com/4316612/148453419-8199e093-f46f-4128-93ec-0e39c3091e0a.png)
Journal pins underneath overlay, transparency added to show where they are

![image](https://user-images.githubusercontent.com/4316612/148453486-9f9201bf-b425-45a0-b2d0-d1dd75b9956c.png)
Journal pins not visible, opacity set to 100%

**Comment by UranusBytes** [comment]
Resolved in 0.2.0
