### ISSUE TITLE
[Feature] Option for the SimpleFog layer to be before/behind the FXMaster layer

### ISSUE THREAD

**Issue by yjeroen** [League-of-Foundry-Developers/simplefog#47]
Currently (with Foundry 9.xxx), the SimpleFog is above the FXMaster layer.

That creates a cool effect:
![image](https://user-images.githubusercontent.com/1303988/152232252-df158044-329b-427c-aae2-0ac29cf7bcee.png)

But it would also be great if we could have the SimpleFog layer behind the FXMaster layer, as a seperate option.

**Comment by UranusBytes** [comment]
Resolved in 0.2.0
