### ISSUE TITLE
image brightness difference between map and overlay

### ISSUE THREAD

**Issue by modzy2** [League-of-Foundry-Developers/simplefog#48]
With base map and overlay set to be copies of the same image, there is a slight brightness or color balance difference between the rendering of the base map and the overlay.  The RGB values where the overlay is showing are approximately 6% higher than the base map.
![hid1](https://user-images.githubusercontent.com/80451044/155653139-2a42f211-9d9c-4848-8310-9ab49d0a6ba4.jpg)
(lower quarter of this image is a revealed area)
While there is still a visible line between the areas (even with blur radius 0, see  #46 ), there is also a visible lightening of the colors from revealed to hidden areas.

(the use case is to have a slightly edited map image to reveal placenames/landmarks etc as map is explored)

**Comment by UranusBytes** [comment]
I did some testing, and I think I can at least reproduce what you are describing, but want to confirm some details (see question below).


Downloaded medium resolution map from https://dnd.wizards.com/articles/features/map-faer%C3%BCn
Running
- bare 5e system (no changes)
- foundry VTT v9 build 269
- GM browser - chrome (latest - v102.0.5005.63)
- Player browser - same chrome in incognito
Create a new scene using med res map as background; disable token vision and fog exploration for scene
Enable SimpleFog, set Fog Overlay Image to same image as scene background
Reveal a small amount around the name "Triboar"

What I noticed is that if the Blur Radius is set to the default of 5, then the revealed area does appear slightly dark, but if the Blur Radius is set to 0, the revealed area does not appear darker.  I tested this with a second scene that was a pure bright color (red)

GM View of scene:
![issue-48_1](https://user-images.githubusercontent.com/11236319/170392016-443d1338-845f-4d3a-8105-d76b5f38f249.jpg)

Player View with Blur Radius 5:
![issue-48_2](https://user-images.githubusercontent.com/11236319/170392250-e8be3f8d-0fd4-497d-ace8-23d9af6a610f.jpg)

Player View with Blur Radius 0:
![issue-48_3](https://user-images.githubusercontent.com/11236319/170392363-3c6ee8e7-fb3e-43d6-8b68-f27ae7bdc033.jpg)

Can you please confirm what the Blur Radius in Simple Fog is currently configured for you?

**Comment by Derinzed** [comment]
sorry to resurrect a closed issue, but is there any way to remove that faint outline with blur radius 0?  I'm trying to mask labels off for my party and have them be unaware that they exist until I reveal it to them.

**Comment by UranusBytes** [comment]
@Derinzed ~Can you please provide a screenshot of what you are seeing?  Preferably both a DM and player view.~

I see what you're asking about.  New issue opened #74
