### ISSUE TITLE
Measurements not visible

### ISSUE THREAD

**Issue by DouglasKims** [League-of-Foundry-Developers/simplefog#49]
Players cannot use the measurement tools on maps, as it's rendered below the fog.

![image](https://user-images.githubusercontent.com/58522726/170121600-908513dd-c67b-492d-bda0-0699ad596cb9.png)

**Comment by UranusBytes** [comment]
I can confirm that the measurement tool is rendered below both the Opacity Color fog and Overlay Image fog...

I'll look into this further...

**Comment by DouglasKims** [comment]
Nice, thanks for looking into this.

Ideally, it'd be great if there was an option in the settings to choose if tiles, measurements, tokens, and other things are rendered above or below the fog.

**Comment by UranusBytes** [comment]
Resolve in release 0.2.0
