### ISSUE TITLE
Infinite update

### ISSUE THREAD

**Issue by notrealdan** [League-of-Foundry-Developers/simplefog#64]
The module.json in the 0.2.1 zip file still points to version 0.2.0, so Foundry always wants to update it, but ends up with 0.2.0 instead of 0.2.1.

**Comment by r-valyar** [comment]
I confirm the issue:

![image](https://user-images.githubusercontent.com/63558984/173292419-406e25c2-606b-438c-8164-b4636586d9b6.png)

**Comment by UranusBytes** [comment]
Thanks for reporting.  Module file updated.  Maybe I'll eventually figure out the automated release github action.  :frowning_face:
