### ISSUE TITLE
SimpleFog prevents Scene from rending

### ISSUE THREAD

**Issue by Havoclivekiller** [League-of-Foundry-Developers/simplefog#7]
The newest version of Foundry (0.7.8) and Dnd (1.2.0) has compatibility issues with SimpleFog. It prevents the whole scene(s) to render.

**Comment by crhampton1** [comment]
I will take a look!

**Comment by crhampton1** [comment]
@Havoclivekiller, I have not been able to replicate any issues. Could you tell me a couple of things so I can try and see what might be causing that for you.

1) Does this occur from a new scene or old scene? Or both?
2) Do you have any other modules loaded, and if so, does it happen with all of them turned off?
3) Can you open your developers tools and let me know if there are any errors when you try to move scenes?
4) Anything else you might think could help.

Sorry for the issues!

**Comment by akrigline** [comment]
@Havoclivekiller please try uninstalling and reinstalling simplefog. Ensure you are running version `1.1.15`, see if it replicates with that version.

**Comment by Havoclivekiller** [comment]
Reinstall helped. Should have done it in the first place. Thank you.
