### ISSUE TITLE
Looking to Sponsor v10 Development

### ISSUE THREAD

**Issue by bryancasler** [League-of-Foundry-Developers/simplefog#73]
Hi @UranusBytes, I'd like to help sponsor v10 Development. I tried posting in the League's monetization Discord channel but didn't get any nibbles. Figured I'd come back here and try again.

**Comment by Conandy1970** [comment]
I'd throw money at this if it would get this module online for v10.  I am still using v9.280 until I have simple fog again.  It is fundamental to the way I run games.

**Comment by UranusBytes** [comment]
If you want to show "thanks" for v10 development on Simplefog, please make a donation to the Red Cross - https://www.redcross.org/donate/donation.html/
