### ISSUE TITLE
Enable Simplefog for multiple scenes

### ISSUE THREAD

**Issue by Nordiii** [League-of-Foundry-Developers/simplefog#8]
I would love to have an option to apply Simplefog to multiple scenes(or every scene) with a button click.
Maybe with additional options like disable token vision on those maps.

**Comment by akrigline** [comment]
A World Setting which enables simplefog by default for newly created scenes seems like a good first step at least.

**Comment by crhampton1** [comment]
Thanks @Nordiii! Great idea.Let me see what I can come up with.

I wonder if finding a way to include it in the scene creation options would be a good place to pu it? Or just turning it on by default like @akrigline said?

**Comment by Nordiii** [comment]
@crhampton1 well I think it should be both.
Add an option to the module settings page with something like "enable by default".
This would then enable the setting by default in the scene creation.
There you could disable it again for this scene tough.

Later you maybe could expand the module settings page with a button activate/deactivate for all scenes. In case you imported a campaign from roll 20 without walls etc.

**Comment by crhampton1** [comment]
Hey @Nordiii , just letting you know I pushed 0.1.16 with this enhancement. I wasn't able to find a good way to do the last part, though.

<img width="487" alt="image" src="https://user-images.githubusercontent.com/1928925/102678421-5b619400-4176-11eb-8a2b-3a3c0e54c157.png">

If you go into Simplefog settings and check the box at the bottom, and then please "make current settings default", then every scene you make will have fog auto enabled. You can toggle fog on/off for a particular scene by clicking the eye at the top of the controls.

This might also cover the last part. When you load the maps from another location, as long as you have that setting activated, then it should also turn on the fog. The only reason it wouldn't is if you have already made a change, thus activating history.

Update and let me know if it works! Open this ticket back up if you have any issues.

Thanks!

**Comment by Nordiii** [comment]
Works well for new scenes now, thanks for the quick reply and update!

Would it be possible to have a macro add necessary data to existing scenes enabling simplefog? (Going to import 40+ maps from roll20)
