### ISSUE TITLE
Simple Fog Layer Icon does not show submenu v10

### ISSUE THREAD

**Issue by kefyn** [League-of-Foundry-Developers/simplefog#82]
Having trouble with V10. The cloud icon appears to the left, but pressing it does not bring up the submenu.

Is thi something that others have experienced?

**Comment by tsimnujhawj** [comment]
simplefog is not working in v10. It seems to be related to the SightLayer, as noted [here](https://github.com/League-of-Foundry-Developers/simplefog/issues/78). I haven't worked with FVTT modules or know the API, but I've cloned the repo and I'm looking to see what needs to be done to get it running on v10.

**Comment by kefyn** [comment]
Thanks,

I've dropped back to 9 and it works fine. Stream View doesn't work on 9, but simple fog is more important for my setup.

Looking forward to simple fog working on v10. All the best with that.

Regards,
Kefyn

Sent from my phone
________________________________

**Comment by UranusBytes** [comment]
Support for v10 is actively under development, but no ETA for full support at this time.

https://github.com/League-of-Foundry-Developers/simplefog/issues/78
