### ISSUE TITLE
v10 Migration Support

### ISSUE THREAD

**Issue by UranusBytes** [League-of-Foundry-Developers/simplefog#90]
Migrate scenes from v9 to v10

**Comment by mattd** [comment]
Any update on the timing of this?

**Comment by UranusBytes** [comment]
Development was paused due to "life", but I'm hoping to give it some attention this week to release a solid beta...

**Comment by porschiey-alt** [comment]
I'm not in the league of developers, but I coded a quick fix today that unblocks me from running my campaigns until there is a more legit/official release. 

Install directly via link:
https://raw.githubusercontent.com/porschiey-alt/simplefog/master/module.json

The GitHub release:
https://github.com/porschiey-alt/simplefog/releases/tag/release

(It still uses some APIs that apparently will be depreciated in the future. YMMV)

Edit: it's still pretty buggy. Can only use the brush tool and only on the active scene after refresh. Might work on a real fix tomorrow

**Comment by UranusBytes** [comment]
v0.3.0 has been released with v10 support.
